### ISSUE TITLE
大佬的路由器是哪个批次的？

### ISSUE THREAD

**Issue by fun-li** [bwnqx/openwrt-rax3000m#1]
如题

**Comment by bwnqx** [comment]
不是大佬啦，我也是小白一个。。。。。。
我这里两台3km,一台0515，一台1027，硬件是一样的，固件通刷

**Comment by fun-li** [comment]
看到您编译的不是https://github.com/hanwckf/immortalwrt-mt798x 而是fork这个仓库的另外一个版本，有啥区别吗

**Comment by bwnqx** [comment]
padavanonly这个库使用了H3C NX30 PRO的高功率eeprom,5Gwifi的功率提升到了24dBm，3km原厂为22dBm

**Comment by fun-li** [comment]
谢谢答疑，明天我的1124版本到货，那我直接用您编译的固件😄
