### ISSUE TITLE
大佬，237config编译出错了

### ISSUE THREAD

**Issue by jaove** [bwnqx/openwrt-rax3000m#2]
ERROR: package/istore/luci-app-store/luci/luci-app-store failed to build.
转入单线程也无法编译完成：
ime: package/istore/luci-app-store/luci/luci-app-store/compile#1.65#0.11#1.75
    ERROR: package/istore/luci-app-store/luci/luci-app-store failed to build.

**Comment by bwnqx** [comment]
上游源码仓库更新了istore界面，我这个还是老的config，所以报错了，回头我传个新的config.

**Comment by bwnqx** [comment]
还不是config的事。。。。。。。
我问了下源码的大佬，大佬说是云编译可能环境有问题，导致istore报错。不知道啥情况我本地编译也没过。
源码把istore删掉了，可以正常云编译。

**Comment by jaove** [comment]
大佬辛苦！

**Comment by bwnqx** [comment]
123
